/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface AuditLog {
  'id' : AuditLogId,
  'action' : string,
  'oldValue' : string,
  'userId' : UserId,
  'newValue' : string,
  'entityId' : bigint,
  'timestamp' : Timestamp,
  'entityType' : string,
}
export interface AuditLogFilter {
  'dateTo' : [] | [Timestamp],
  'userId' : [] | [UserId],
  'entityType' : [] | [string],
  'dateFrom' : [] | [Timestamp],
}
export type AuditLogId = bigint;
export interface Bill {
  'id' : BillId,
  'status' : BillStatus,
  'month' : string,
  'netAmount' : bigint,
  'studentId' : StudentId,
  'fineAmount' : bigint,
  'discountAmount' : bigint,
  'createdAt' : Timestamp,
  'dueDate' : Timestamp,
  'classId' : ClassId,
  'academicYear' : string,
  'totalAmount' : bigint,
  'billNumber' : string,
  'feeComponents' : Array<FeeComponent>,
}
export interface BillFilter {
  'status' : [] | [BillStatus],
  'month' : [] | [string],
  'studentId' : [] | [StudentId],
  'classId' : [] | [ClassId],
}
export type BillId = bigint;
export type BillStatus = { 'Paid' : null } |
  { 'Overdue' : null } |
  { 'Partial' : null } |
  { 'Cancelled' : null } |
  { 'Pending' : null };
export interface Class {
  'id' : ClassId,
  'classTeacherId' : [] | [UserId],
  'name' : string,
  'createdAt' : Timestamp,
  'section' : string,
  'academicYear' : string,
  'capacity' : bigint,
  'studentCount' : bigint,
}
export type ClassId = bigint;
export interface ClassInput {
  'classTeacherId' : [] | [UserId],
  'name' : string,
  'section' : string,
  'academicYear' : string,
  'capacity' : bigint,
}
export interface DashboardStats {
  'todayCollection' : bigint,
  'totalCollected' : bigint,
  'totalStudents' : bigint,
  'dueStudentsCount' : bigint,
  'pendingFees' : bigint,
}
export type FeeCategory = { 'Library' : null } |
  { 'Admission' : null } |
  { 'Exam' : null } |
  { 'Tuition' : null } |
  { 'Custom' : null } |
  { 'Miscellaneous' : null } |
  { 'Transport' : null } |
  { 'Hostel' : null };
export interface FeeComponent {
  'fine' : bigint,
  'discount' : bigint,
  'category' : FeeCategory,
  'amount' : bigint,
}
export interface FeeStructure {
  'id' : FeeStructureId,
  'createdAt' : Timestamp,
  'discountPercent' : bigint,
  'classId' : ClassId,
  'dueDayOfMonth' : bigint,
  'isActive' : boolean,
  'academicYear' : string,
  'category' : FeeCategory,
  'fineRatePercent' : bigint,
  'paymentPlan' : PaymentPlan,
  'amount' : bigint,
  'customCategoryName' : string,
}
export type FeeStructureId = bigint;
export interface FeeStructureInput {
  'discountPercent' : bigint,
  'classId' : ClassId,
  'dueDayOfMonth' : bigint,
  'academicYear' : string,
  'category' : FeeCategory,
  'fineRatePercent' : bigint,
  'paymentPlan' : PaymentPlan,
  'amount' : bigint,
  'customCategoryName' : string,
}
export interface Notification {
  'id' : NotificationId,
  'studentId' : StudentId,
  'notifType' : NotificationType,
  'createdAt' : Timestamp,
  'isRead' : boolean,
  'message' : string,
  'recipientPrincipal' : Principal,
}
export type NotificationId = bigint;
export type NotificationType = { 'FeeReminder' : null } |
  { 'BillGenerated' : null } |
  { 'PaymentConfirmation' : null } |
  { 'OverdueAlert' : null };
export interface Payment {
  'id' : PaymentId,
  'method' : PaymentMethod,
  'studentId' : StudentId,
  'referenceNumber' : string,
  'createdAt' : Timestamp,
  'notes' : string,
  'paymentDate' : Timestamp,
  'receiptId' : [] | [ReceiptId],
  'amount' : bigint,
  'billId' : BillId,
}
export interface PaymentFilter {
  'method' : [] | [PaymentMethod],
  'studentId' : [] | [StudentId],
  'dateTo' : [] | [Timestamp],
  'dateFrom' : [] | [Timestamp],
}
export type PaymentId = bigint;
export interface PaymentInput {
  'method' : PaymentMethod,
  'studentId' : StudentId,
  'referenceNumber' : string,
  'notes' : string,
  'amount' : bigint,
  'billId' : BillId,
}
export type PaymentMethod = { 'UPI' : null } |
  { 'Card' : null } |
  { 'Cash' : null } |
  { 'Online' : null } |
  { 'BankTransfer' : null };
export type PaymentPlan = { 'Quarterly' : null } |
  { 'Monthly' : null } |
  { 'Yearly' : null };
export interface Receipt {
  'id' : ReceiptId,
  'method' : PaymentMethod,
  'studentId' : StudentId,
  'isDuplicate' : boolean,
  'paymentId' : PaymentId,
  'paymentDate' : Timestamp,
  'issuedAt' : Timestamp,
  'amount' : bigint,
  'billId' : BillId,
  'receiptNumber' : string,
  'qrData' : string,
}
export interface ReceiptFilter {
  'studentId' : [] | [StudentId],
  'dateTo' : [] | [Timestamp],
  'dateFrom' : [] | [Timestamp],
}
export type ReceiptId = bigint;
export type Result = { 'ok' : Student } |
  { 'err' : string };
export type Result_1 = { 'ok' : FeeStructure } |
  { 'err' : string };
export type Result_2 = { 'ok' : Class } |
  { 'err' : string };
export type Result_3 = { 'ok' : Bill } |
  { 'err' : string };
export type Result_4 = { 'ok' : User } |
  { 'err' : string };
export type Result_5 = { 'ok' : Receipt } |
  { 'err' : string };
export type Result_6 = { 'ok' : boolean } |
  { 'err' : string };
export type Result_7 = { 'ok' : Array<User> } |
  { 'err' : string };
export type Result_8 = { 'ok' : Array<Bill> } |
  { 'err' : string };
export type Result_9 = { 'ok' : Notification } |
  { 'err' : string };
export type Role = { 'Teacher' : null } |
  { 'SuperAdmin' : null } |
  { 'SchoolAdmin' : null } |
  { 'Accountant' : null };
export interface Student {
  'id' : StudentId,
  'dob' : string,
  'parentEmail' : string,
  'status' : StudentStatus,
  'name' : string,
  'createdAt' : Timestamp,
  'parentPhone' : string,
  'photoUrl' : string,
  'classId' : ClassId,
  'admissionNumber' : string,
  'academicYear' : string,
  'sectionId' : bigint,
  'rollNumber' : string,
  'address' : string,
  'gender' : string,
  'parentName' : string,
}
export interface StudentFilter {
  'status' : [] | [StudentStatus],
  'classId' : [] | [ClassId],
  'searchTerm' : [] | [string],
  'academicYear' : [] | [string],
}
export type StudentId = bigint;
export interface StudentInput {
  'dob' : string,
  'parentEmail' : string,
  'name' : string,
  'parentPhone' : string,
  'photoUrl' : string,
  'classId' : ClassId,
  'admissionNumber' : string,
  'academicYear' : string,
  'sectionId' : bigint,
  'rollNumber' : string,
  'address' : string,
  'gender' : string,
  'parentName' : string,
}
export type StudentStatus = { 'Inactive' : null } |
  { 'Active' : null };
export type Timestamp = bigint;
export interface User {
  'id' : UserId,
  'status' : UserStatus,
  'principal' : Principal,
  'name' : string,
  'createdAt' : Timestamp,
  'role' : Role,
  'email' : string,
  'lastLogin' : Timestamp,
}
export type UserId = bigint;
export type UserStatus = { 'Inactive' : null } |
  { 'Active' : null };
export interface _SERVICE {
  'addAuditLog' : ActorMethod<
    [string, string, bigint, string, string],
    Result_6
  >,
  'addClass' : ActorMethod<[ClassInput], Result_2>,
  'addNotification' : ActorMethod<
    [NotificationType, StudentId, string],
    Result_9
  >,
  'addStudent' : ActorMethod<[StudentInput], Result>,
  'createFeeStructure' : ActorMethod<[FeeStructureInput], Result_1>,
  'deleteClass' : ActorMethod<[ClassId], Result_6>,
  'deleteFeeStructure' : ActorMethod<[FeeStructureId], Result_6>,
  'deleteStudent' : ActorMethod<[StudentId], Result_6>,
  'duplicateReceipt' : ActorMethod<[ReceiptId], Result_5>,
  'generateBills' : ActorMethod<[ClassId, string, string], Result_8>,
  'getAuditLogs' : ActorMethod<[AuditLogFilter], Array<AuditLog>>,
  'getBill' : ActorMethod<[BillId], [] | [Bill]>,
  'getBills' : ActorMethod<[BillFilter], Array<Bill>>,
  'getClass' : ActorMethod<[ClassId], [] | [Class]>,
  'getClasses' : ActorMethod<[[] | [string]], Array<Class>>,
  'getFeeStructures' : ActorMethod<
    [[] | [ClassId], [] | [string]],
    Array<FeeStructure>
  >,
  'getNotifications' : ActorMethod<[], Array<Notification>>,
  'getPayments' : ActorMethod<[PaymentFilter], Array<Payment>>,
  'getReceipt' : ActorMethod<[ReceiptId], [] | [Receipt]>,
  'getReceipts' : ActorMethod<[ReceiptFilter], Array<Receipt>>,
  'getStats' : ActorMethod<[], DashboardStats>,
  'getStudent' : ActorMethod<[StudentId], [] | [Student]>,
  'getStudents' : ActorMethod<[StudentFilter], Array<Student>>,
  'getUserByPrincipal' : ActorMethod<[], [] | [User]>,
  'listUsers' : ActorMethod<[], Result_7>,
  'markNotificationRead' : ActorMethod<[NotificationId], Result_6>,
  'recordPayment' : ActorMethod<[PaymentInput], Result_5>,
  'registerUser' : ActorMethod<[string, string, Role], Result_4>,
  'updateBillStatus' : ActorMethod<[BillId, BillStatus], Result_3>,
  'updateClass' : ActorMethod<[ClassId, ClassInput], Result_2>,
  'updateFeeStructure' : ActorMethod<
    [FeeStructureId, FeeStructureInput],
    Result_1
  >,
  'updateLastLogin' : ActorMethod<[], undefined>,
  'updateStudent' : ActorMethod<[StudentId, StudentInput], Result>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];