/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Result_6 = IDL.Variant({ 'ok' : IDL.Bool, 'err' : IDL.Text });
export const UserId = IDL.Nat;
export const ClassInput = IDL.Record({
  'classTeacherId' : IDL.Opt(UserId),
  'name' : IDL.Text,
  'section' : IDL.Text,
  'academicYear' : IDL.Text,
  'capacity' : IDL.Nat,
});
export const ClassId = IDL.Nat;
export const Timestamp = IDL.Int;
export const Class = IDL.Record({
  'id' : ClassId,
  'classTeacherId' : IDL.Opt(UserId),
  'name' : IDL.Text,
  'createdAt' : Timestamp,
  'section' : IDL.Text,
  'academicYear' : IDL.Text,
  'capacity' : IDL.Nat,
  'studentCount' : IDL.Nat,
});
export const Result_2 = IDL.Variant({ 'ok' : Class, 'err' : IDL.Text });
export const NotificationType = IDL.Variant({
  'FeeReminder' : IDL.Null,
  'BillGenerated' : IDL.Null,
  'PaymentConfirmation' : IDL.Null,
  'OverdueAlert' : IDL.Null,
});
export const StudentId = IDL.Nat;
export const NotificationId = IDL.Nat;
export const Notification = IDL.Record({
  'id' : NotificationId,
  'studentId' : StudentId,
  'notifType' : NotificationType,
  'createdAt' : Timestamp,
  'isRead' : IDL.Bool,
  'message' : IDL.Text,
  'recipientPrincipal' : IDL.Principal,
});
export const Result_9 = IDL.Variant({ 'ok' : Notification, 'err' : IDL.Text });
export const StudentInput = IDL.Record({
  'dob' : IDL.Text,
  'parentEmail' : IDL.Text,
  'name' : IDL.Text,
  'parentPhone' : IDL.Text,
  'photoUrl' : IDL.Text,
  'classId' : ClassId,
  'admissionNumber' : IDL.Text,
  'academicYear' : IDL.Text,
  'sectionId' : IDL.Nat,
  'rollNumber' : IDL.Text,
  'address' : IDL.Text,
  'gender' : IDL.Text,
  'parentName' : IDL.Text,
});
export const StudentStatus = IDL.Variant({
  'Inactive' : IDL.Null,
  'Active' : IDL.Null,
});
export const Student = IDL.Record({
  'id' : StudentId,
  'dob' : IDL.Text,
  'parentEmail' : IDL.Text,
  'status' : StudentStatus,
  'name' : IDL.Text,
  'createdAt' : Timestamp,
  'parentPhone' : IDL.Text,
  'photoUrl' : IDL.Text,
  'classId' : ClassId,
  'admissionNumber' : IDL.Text,
  'academicYear' : IDL.Text,
  'sectionId' : IDL.Nat,
  'rollNumber' : IDL.Text,
  'address' : IDL.Text,
  'gender' : IDL.Text,
  'parentName' : IDL.Text,
});
export const Result = IDL.Variant({ 'ok' : Student, 'err' : IDL.Text });
export const FeeCategory = IDL.Variant({
  'Library' : IDL.Null,
  'Admission' : IDL.Null,
  'Exam' : IDL.Null,
  'Tuition' : IDL.Null,
  'Custom' : IDL.Null,
  'Miscellaneous' : IDL.Null,
  'Transport' : IDL.Null,
  'Hostel' : IDL.Null,
});
export const PaymentPlan = IDL.Variant({
  'Quarterly' : IDL.Null,
  'Monthly' : IDL.Null,
  'Yearly' : IDL.Null,
});
export const FeeStructureInput = IDL.Record({
  'discountPercent' : IDL.Nat,
  'classId' : ClassId,
  'dueDayOfMonth' : IDL.Nat,
  'academicYear' : IDL.Text,
  'category' : FeeCategory,
  'fineRatePercent' : IDL.Nat,
  'paymentPlan' : PaymentPlan,
  'amount' : IDL.Nat,
  'customCategoryName' : IDL.Text,
});
export const FeeStructureId = IDL.Nat;
export const FeeStructure = IDL.Record({
  'id' : FeeStructureId,
  'createdAt' : Timestamp,
  'discountPercent' : IDL.Nat,
  'classId' : ClassId,
  'dueDayOfMonth' : IDL.Nat,
  'isActive' : IDL.Bool,
  'academicYear' : IDL.Text,
  'category' : FeeCategory,
  'fineRatePercent' : IDL.Nat,
  'paymentPlan' : PaymentPlan,
  'amount' : IDL.Nat,
  'customCategoryName' : IDL.Text,
});
export const Result_1 = IDL.Variant({ 'ok' : FeeStructure, 'err' : IDL.Text });
export const ReceiptId = IDL.Nat;
export const PaymentMethod = IDL.Variant({
  'UPI' : IDL.Null,
  'Card' : IDL.Null,
  'Cash' : IDL.Null,
  'Online' : IDL.Null,
  'BankTransfer' : IDL.Null,
});
export const PaymentId = IDL.Nat;
export const BillId = IDL.Nat;
export const Receipt = IDL.Record({
  'id' : ReceiptId,
  'method' : PaymentMethod,
  'studentId' : StudentId,
  'isDuplicate' : IDL.Bool,
  'paymentId' : PaymentId,
  'paymentDate' : Timestamp,
  'issuedAt' : Timestamp,
  'amount' : IDL.Nat,
  'billId' : BillId,
  'receiptNumber' : IDL.Text,
  'qrData' : IDL.Text,
});
export const Result_5 = IDL.Variant({ 'ok' : Receipt, 'err' : IDL.Text });
export const BillStatus = IDL.Variant({
  'Paid' : IDL.Null,
  'Overdue' : IDL.Null,
  'Partial' : IDL.Null,
  'Cancelled' : IDL.Null,
  'Pending' : IDL.Null,
});
export const FeeComponent = IDL.Record({
  'fine' : IDL.Nat,
  'discount' : IDL.Nat,
  'category' : FeeCategory,
  'amount' : IDL.Nat,
});
export const Bill = IDL.Record({
  'id' : BillId,
  'status' : BillStatus,
  'month' : IDL.Text,
  'netAmount' : IDL.Nat,
  'studentId' : StudentId,
  'fineAmount' : IDL.Nat,
  'discountAmount' : IDL.Nat,
  'createdAt' : Timestamp,
  'dueDate' : Timestamp,
  'classId' : ClassId,
  'academicYear' : IDL.Text,
  'totalAmount' : IDL.Nat,
  'billNumber' : IDL.Text,
  'feeComponents' : IDL.Vec(FeeComponent),
});
export const Result_8 = IDL.Variant({ 'ok' : IDL.Vec(Bill), 'err' : IDL.Text });
export const AuditLogFilter = IDL.Record({
  'dateTo' : IDL.Opt(Timestamp),
  'userId' : IDL.Opt(UserId),
  'entityType' : IDL.Opt(IDL.Text),
  'dateFrom' : IDL.Opt(Timestamp),
});
export const AuditLogId = IDL.Nat;
export const AuditLog = IDL.Record({
  'id' : AuditLogId,
  'action' : IDL.Text,
  'oldValue' : IDL.Text,
  'userId' : UserId,
  'newValue' : IDL.Text,
  'entityId' : IDL.Nat,
  'timestamp' : Timestamp,
  'entityType' : IDL.Text,
});
export const BillFilter = IDL.Record({
  'status' : IDL.Opt(BillStatus),
  'month' : IDL.Opt(IDL.Text),
  'studentId' : IDL.Opt(StudentId),
  'classId' : IDL.Opt(ClassId),
});
export const PaymentFilter = IDL.Record({
  'method' : IDL.Opt(PaymentMethod),
  'studentId' : IDL.Opt(StudentId),
  'dateTo' : IDL.Opt(Timestamp),
  'dateFrom' : IDL.Opt(Timestamp),
});
export const Payment = IDL.Record({
  'id' : PaymentId,
  'method' : PaymentMethod,
  'studentId' : StudentId,
  'referenceNumber' : IDL.Text,
  'createdAt' : Timestamp,
  'notes' : IDL.Text,
  'paymentDate' : Timestamp,
  'receiptId' : IDL.Opt(ReceiptId),
  'amount' : IDL.Nat,
  'billId' : BillId,
});
export const ReceiptFilter = IDL.Record({
  'studentId' : IDL.Opt(StudentId),
  'dateTo' : IDL.Opt(Timestamp),
  'dateFrom' : IDL.Opt(Timestamp),
});
export const DashboardStats = IDL.Record({
  'todayCollection' : IDL.Nat,
  'totalCollected' : IDL.Nat,
  'totalStudents' : IDL.Nat,
  'dueStudentsCount' : IDL.Nat,
  'pendingFees' : IDL.Nat,
});
export const StudentFilter = IDL.Record({
  'status' : IDL.Opt(StudentStatus),
  'classId' : IDL.Opt(ClassId),
  'searchTerm' : IDL.Opt(IDL.Text),
  'academicYear' : IDL.Opt(IDL.Text),
});
export const UserStatus = IDL.Variant({
  'Inactive' : IDL.Null,
  'Active' : IDL.Null,
});
export const Role = IDL.Variant({
  'Teacher' : IDL.Null,
  'SuperAdmin' : IDL.Null,
  'SchoolAdmin' : IDL.Null,
  'Accountant' : IDL.Null,
});
export const User = IDL.Record({
  'id' : UserId,
  'status' : UserStatus,
  'principal' : IDL.Principal,
  'name' : IDL.Text,
  'createdAt' : Timestamp,
  'role' : Role,
  'email' : IDL.Text,
  'lastLogin' : Timestamp,
});
export const Result_7 = IDL.Variant({ 'ok' : IDL.Vec(User), 'err' : IDL.Text });
export const PaymentInput = IDL.Record({
  'method' : PaymentMethod,
  'studentId' : StudentId,
  'referenceNumber' : IDL.Text,
  'notes' : IDL.Text,
  'amount' : IDL.Nat,
  'billId' : BillId,
});
export const Result_4 = IDL.Variant({ 'ok' : User, 'err' : IDL.Text });
export const Result_3 = IDL.Variant({ 'ok' : Bill, 'err' : IDL.Text });

export const idlService = IDL.Service({
  'addAuditLog' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Nat, IDL.Text, IDL.Text],
      [Result_6],
      [],
    ),
  'addClass' : IDL.Func([ClassInput], [Result_2], []),
  'addNotification' : IDL.Func(
      [NotificationType, StudentId, IDL.Text],
      [Result_9],
      [],
    ),
  'addStudent' : IDL.Func([StudentInput], [Result], []),
  'createFeeStructure' : IDL.Func([FeeStructureInput], [Result_1], []),
  'deleteClass' : IDL.Func([ClassId], [Result_6], []),
  'deleteFeeStructure' : IDL.Func([FeeStructureId], [Result_6], []),
  'deleteStudent' : IDL.Func([StudentId], [Result_6], []),
  'duplicateReceipt' : IDL.Func([ReceiptId], [Result_5], []),
  'generateBills' : IDL.Func([ClassId, IDL.Text, IDL.Text], [Result_8], []),
  'getAuditLogs' : IDL.Func([AuditLogFilter], [IDL.Vec(AuditLog)], ['query']),
  'getBill' : IDL.Func([BillId], [IDL.Opt(Bill)], ['query']),
  'getBills' : IDL.Func([BillFilter], [IDL.Vec(Bill)], ['query']),
  'getClass' : IDL.Func([ClassId], [IDL.Opt(Class)], ['query']),
  'getClasses' : IDL.Func([IDL.Opt(IDL.Text)], [IDL.Vec(Class)], ['query']),
  'getFeeStructures' : IDL.Func(
      [IDL.Opt(ClassId), IDL.Opt(IDL.Text)],
      [IDL.Vec(FeeStructure)],
      ['query'],
    ),
  'getNotifications' : IDL.Func([], [IDL.Vec(Notification)], ['query']),
  'getPayments' : IDL.Func([PaymentFilter], [IDL.Vec(Payment)], ['query']),
  'getReceipt' : IDL.Func([ReceiptId], [IDL.Opt(Receipt)], ['query']),
  'getReceipts' : IDL.Func([ReceiptFilter], [IDL.Vec(Receipt)], ['query']),
  'getStats' : IDL.Func([], [DashboardStats], ['query']),
  'getStudent' : IDL.Func([StudentId], [IDL.Opt(Student)], ['query']),
  'getStudents' : IDL.Func([StudentFilter], [IDL.Vec(Student)], ['query']),
  'getUserByPrincipal' : IDL.Func([], [IDL.Opt(User)], ['query']),
  'listUsers' : IDL.Func([], [Result_7], ['query']),
  'markNotificationRead' : IDL.Func([NotificationId], [Result_6], []),
  'recordPayment' : IDL.Func([PaymentInput], [Result_5], []),
  'registerUser' : IDL.Func([IDL.Text, IDL.Text, Role], [Result_4], []),
  'updateBillStatus' : IDL.Func([BillId, BillStatus], [Result_3], []),
  'updateClass' : IDL.Func([ClassId, ClassInput], [Result_2], []),
  'updateFeeStructure' : IDL.Func(
      [FeeStructureId, FeeStructureInput],
      [Result_1],
      [],
    ),
  'updateLastLogin' : IDL.Func([], [], []),
  'updateStudent' : IDL.Func([StudentId, StudentInput], [Result], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Result_6 = IDL.Variant({ 'ok' : IDL.Bool, 'err' : IDL.Text });
  const UserId = IDL.Nat;
  const ClassInput = IDL.Record({
    'classTeacherId' : IDL.Opt(UserId),
    'name' : IDL.Text,
    'section' : IDL.Text,
    'academicYear' : IDL.Text,
    'capacity' : IDL.Nat,
  });
  const ClassId = IDL.Nat;
  const Timestamp = IDL.Int;
  const Class = IDL.Record({
    'id' : ClassId,
    'classTeacherId' : IDL.Opt(UserId),
    'name' : IDL.Text,
    'createdAt' : Timestamp,
    'section' : IDL.Text,
    'academicYear' : IDL.Text,
    'capacity' : IDL.Nat,
    'studentCount' : IDL.Nat,
  });
  const Result_2 = IDL.Variant({ 'ok' : Class, 'err' : IDL.Text });
  const NotificationType = IDL.Variant({
    'FeeReminder' : IDL.Null,
    'BillGenerated' : IDL.Null,
    'PaymentConfirmation' : IDL.Null,
    'OverdueAlert' : IDL.Null,
  });
  const StudentId = IDL.Nat;
  const NotificationId = IDL.Nat;
  const Notification = IDL.Record({
    'id' : NotificationId,
    'studentId' : StudentId,
    'notifType' : NotificationType,
    'createdAt' : Timestamp,
    'isRead' : IDL.Bool,
    'message' : IDL.Text,
    'recipientPrincipal' : IDL.Principal,
  });
  const Result_9 = IDL.Variant({ 'ok' : Notification, 'err' : IDL.Text });
  const StudentInput = IDL.Record({
    'dob' : IDL.Text,
    'parentEmail' : IDL.Text,
    'name' : IDL.Text,
    'parentPhone' : IDL.Text,
    'photoUrl' : IDL.Text,
    'classId' : ClassId,
    'admissionNumber' : IDL.Text,
    'academicYear' : IDL.Text,
    'sectionId' : IDL.Nat,
    'rollNumber' : IDL.Text,
    'address' : IDL.Text,
    'gender' : IDL.Text,
    'parentName' : IDL.Text,
  });
  const StudentStatus = IDL.Variant({
    'Inactive' : IDL.Null,
    'Active' : IDL.Null,
  });
  const Student = IDL.Record({
    'id' : StudentId,
    'dob' : IDL.Text,
    'parentEmail' : IDL.Text,
    'status' : StudentStatus,
    'name' : IDL.Text,
    'createdAt' : Timestamp,
    'parentPhone' : IDL.Text,
    'photoUrl' : IDL.Text,
    'classId' : ClassId,
    'admissionNumber' : IDL.Text,
    'academicYear' : IDL.Text,
    'sectionId' : IDL.Nat,
    'rollNumber' : IDL.Text,
    'address' : IDL.Text,
    'gender' : IDL.Text,
    'parentName' : IDL.Text,
  });
  const Result = IDL.Variant({ 'ok' : Student, 'err' : IDL.Text });
  const FeeCategory = IDL.Variant({
    'Library' : IDL.Null,
    'Admission' : IDL.Null,
    'Exam' : IDL.Null,
    'Tuition' : IDL.Null,
    'Custom' : IDL.Null,
    'Miscellaneous' : IDL.Null,
    'Transport' : IDL.Null,
    'Hostel' : IDL.Null,
  });
  const PaymentPlan = IDL.Variant({
    'Quarterly' : IDL.Null,
    'Monthly' : IDL.Null,
    'Yearly' : IDL.Null,
  });
  const FeeStructureInput = IDL.Record({
    'discountPercent' : IDL.Nat,
    'classId' : ClassId,
    'dueDayOfMonth' : IDL.Nat,
    'academicYear' : IDL.Text,
    'category' : FeeCategory,
    'fineRatePercent' : IDL.Nat,
    'paymentPlan' : PaymentPlan,
    'amount' : IDL.Nat,
    'customCategoryName' : IDL.Text,
  });
  const FeeStructureId = IDL.Nat;
  const FeeStructure = IDL.Record({
    'id' : FeeStructureId,
    'createdAt' : Timestamp,
    'discountPercent' : IDL.Nat,
    'classId' : ClassId,
    'dueDayOfMonth' : IDL.Nat,
    'isActive' : IDL.Bool,
    'academicYear' : IDL.Text,
    'category' : FeeCategory,
    'fineRatePercent' : IDL.Nat,
    'paymentPlan' : PaymentPlan,
    'amount' : IDL.Nat,
    'customCategoryName' : IDL.Text,
  });
  const Result_1 = IDL.Variant({ 'ok' : FeeStructure, 'err' : IDL.Text });
  const ReceiptId = IDL.Nat;
  const PaymentMethod = IDL.Variant({
    'UPI' : IDL.Null,
    'Card' : IDL.Null,
    'Cash' : IDL.Null,
    'Online' : IDL.Null,
    'BankTransfer' : IDL.Null,
  });
  const PaymentId = IDL.Nat;
  const BillId = IDL.Nat;
  const Receipt = IDL.Record({
    'id' : ReceiptId,
    'method' : PaymentMethod,
    'studentId' : StudentId,
    'isDuplicate' : IDL.Bool,
    'paymentId' : PaymentId,
    'paymentDate' : Timestamp,
    'issuedAt' : Timestamp,
    'amount' : IDL.Nat,
    'billId' : BillId,
    'receiptNumber' : IDL.Text,
    'qrData' : IDL.Text,
  });
  const Result_5 = IDL.Variant({ 'ok' : Receipt, 'err' : IDL.Text });
  const BillStatus = IDL.Variant({
    'Paid' : IDL.Null,
    'Overdue' : IDL.Null,
    'Partial' : IDL.Null,
    'Cancelled' : IDL.Null,
    'Pending' : IDL.Null,
  });
  const FeeComponent = IDL.Record({
    'fine' : IDL.Nat,
    'discount' : IDL.Nat,
    'category' : FeeCategory,
    'amount' : IDL.Nat,
  });
  const Bill = IDL.Record({
    'id' : BillId,
    'status' : BillStatus,
    'month' : IDL.Text,
    'netAmount' : IDL.Nat,
    'studentId' : StudentId,
    'fineAmount' : IDL.Nat,
    'discountAmount' : IDL.Nat,
    'createdAt' : Timestamp,
    'dueDate' : Timestamp,
    'classId' : ClassId,
    'academicYear' : IDL.Text,
    'totalAmount' : IDL.Nat,
    'billNumber' : IDL.Text,
    'feeComponents' : IDL.Vec(FeeComponent),
  });
  const Result_8 = IDL.Variant({ 'ok' : IDL.Vec(Bill), 'err' : IDL.Text });
  const AuditLogFilter = IDL.Record({
    'dateTo' : IDL.Opt(Timestamp),
    'userId' : IDL.Opt(UserId),
    'entityType' : IDL.Opt(IDL.Text),
    'dateFrom' : IDL.Opt(Timestamp),
  });
  const AuditLogId = IDL.Nat;
  const AuditLog = IDL.Record({
    'id' : AuditLogId,
    'action' : IDL.Text,
    'oldValue' : IDL.Text,
    'userId' : UserId,
    'newValue' : IDL.Text,
    'entityId' : IDL.Nat,
    'timestamp' : Timestamp,
    'entityType' : IDL.Text,
  });
  const BillFilter = IDL.Record({
    'status' : IDL.Opt(BillStatus),
    'month' : IDL.Opt(IDL.Text),
    'studentId' : IDL.Opt(StudentId),
    'classId' : IDL.Opt(ClassId),
  });
  const PaymentFilter = IDL.Record({
    'method' : IDL.Opt(PaymentMethod),
    'studentId' : IDL.Opt(StudentId),
    'dateTo' : IDL.Opt(Timestamp),
    'dateFrom' : IDL.Opt(Timestamp),
  });
  const Payment = IDL.Record({
    'id' : PaymentId,
    'method' : PaymentMethod,
    'studentId' : StudentId,
    'referenceNumber' : IDL.Text,
    'createdAt' : Timestamp,
    'notes' : IDL.Text,
    'paymentDate' : Timestamp,
    'receiptId' : IDL.Opt(ReceiptId),
    'amount' : IDL.Nat,
    'billId' : BillId,
  });
  const ReceiptFilter = IDL.Record({
    'studentId' : IDL.Opt(StudentId),
    'dateTo' : IDL.Opt(Timestamp),
    'dateFrom' : IDL.Opt(Timestamp),
  });
  const DashboardStats = IDL.Record({
    'todayCollection' : IDL.Nat,
    'totalCollected' : IDL.Nat,
    'totalStudents' : IDL.Nat,
    'dueStudentsCount' : IDL.Nat,
    'pendingFees' : IDL.Nat,
  });
  const StudentFilter = IDL.Record({
    'status' : IDL.Opt(StudentStatus),
    'classId' : IDL.Opt(ClassId),
    'searchTerm' : IDL.Opt(IDL.Text),
    'academicYear' : IDL.Opt(IDL.Text),
  });
  const UserStatus = IDL.Variant({
    'Inactive' : IDL.Null,
    'Active' : IDL.Null,
  });
  const Role = IDL.Variant({
    'Teacher' : IDL.Null,
    'SuperAdmin' : IDL.Null,
    'SchoolAdmin' : IDL.Null,
    'Accountant' : IDL.Null,
  });
  const User = IDL.Record({
    'id' : UserId,
    'status' : UserStatus,
    'principal' : IDL.Principal,
    'name' : IDL.Text,
    'createdAt' : Timestamp,
    'role' : Role,
    'email' : IDL.Text,
    'lastLogin' : Timestamp,
  });
  const Result_7 = IDL.Variant({ 'ok' : IDL.Vec(User), 'err' : IDL.Text });
  const PaymentInput = IDL.Record({
    'method' : PaymentMethod,
    'studentId' : StudentId,
    'referenceNumber' : IDL.Text,
    'notes' : IDL.Text,
    'amount' : IDL.Nat,
    'billId' : BillId,
  });
  const Result_4 = IDL.Variant({ 'ok' : User, 'err' : IDL.Text });
  const Result_3 = IDL.Variant({ 'ok' : Bill, 'err' : IDL.Text });
  
  return IDL.Service({
    'addAuditLog' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Nat, IDL.Text, IDL.Text],
        [Result_6],
        [],
      ),
    'addClass' : IDL.Func([ClassInput], [Result_2], []),
    'addNotification' : IDL.Func(
        [NotificationType, StudentId, IDL.Text],
        [Result_9],
        [],
      ),
    'addStudent' : IDL.Func([StudentInput], [Result], []),
    'createFeeStructure' : IDL.Func([FeeStructureInput], [Result_1], []),
    'deleteClass' : IDL.Func([ClassId], [Result_6], []),
    'deleteFeeStructure' : IDL.Func([FeeStructureId], [Result_6], []),
    'deleteStudent' : IDL.Func([StudentId], [Result_6], []),
    'duplicateReceipt' : IDL.Func([ReceiptId], [Result_5], []),
    'generateBills' : IDL.Func([ClassId, IDL.Text, IDL.Text], [Result_8], []),
    'getAuditLogs' : IDL.Func([AuditLogFilter], [IDL.Vec(AuditLog)], ['query']),
    'getBill' : IDL.Func([BillId], [IDL.Opt(Bill)], ['query']),
    'getBills' : IDL.Func([BillFilter], [IDL.Vec(Bill)], ['query']),
    'getClass' : IDL.Func([ClassId], [IDL.Opt(Class)], ['query']),
    'getClasses' : IDL.Func([IDL.Opt(IDL.Text)], [IDL.Vec(Class)], ['query']),
    'getFeeStructures' : IDL.Func(
        [IDL.Opt(ClassId), IDL.Opt(IDL.Text)],
        [IDL.Vec(FeeStructure)],
        ['query'],
      ),
    'getNotifications' : IDL.Func([], [IDL.Vec(Notification)], ['query']),
    'getPayments' : IDL.Func([PaymentFilter], [IDL.Vec(Payment)], ['query']),
    'getReceipt' : IDL.Func([ReceiptId], [IDL.Opt(Receipt)], ['query']),
    'getReceipts' : IDL.Func([ReceiptFilter], [IDL.Vec(Receipt)], ['query']),
    'getStats' : IDL.Func([], [DashboardStats], ['query']),
    'getStudent' : IDL.Func([StudentId], [IDL.Opt(Student)], ['query']),
    'getStudents' : IDL.Func([StudentFilter], [IDL.Vec(Student)], ['query']),
    'getUserByPrincipal' : IDL.Func([], [IDL.Opt(User)], ['query']),
    'listUsers' : IDL.Func([], [Result_7], ['query']),
    'markNotificationRead' : IDL.Func([NotificationId], [Result_6], []),
    'recordPayment' : IDL.Func([PaymentInput], [Result_5], []),
    'registerUser' : IDL.Func([IDL.Text, IDL.Text, Role], [Result_4], []),
    'updateBillStatus' : IDL.Func([BillId, BillStatus], [Result_3], []),
    'updateClass' : IDL.Func([ClassId, ClassInput], [Result_2], []),
    'updateFeeStructure' : IDL.Func(
        [FeeStructureId, FeeStructureInput],
        [Result_1],
        [],
      ),
    'updateLastLogin' : IDL.Func([], [], []),
    'updateStudent' : IDL.Func([StudentId, StudentInput], [Result], []),
  });
};

export const init = ({ IDL }) => { return []; };