/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface Class {
    id: ClassId;
    classTeacherId?: UserId;
    name: string;
    createdAt: Timestamp;
    section: string;
    academicYear: string;
    capacity: bigint;
    studentCount: bigint;
}
export interface StudentFilter {
    status?: StudentStatus;
    classId?: ClassId;
    searchTerm?: string;
    academicYear?: string;
}
export type Timestamp = bigint;
export type Result_2 = {
    __kind__: "ok";
    ok: Class;
} | {
    __kind__: "err";
    err: string;
};
export interface AuditLog {
    id: AuditLogId;
    action: string;
    oldValue: string;
    userId: UserId;
    newValue: string;
    entityId: bigint;
    timestamp: Timestamp;
    entityType: string;
}
export interface FeeComponent {
    fine: bigint;
    discount: bigint;
    category: FeeCategory;
    amount: bigint;
}
export interface StudentInput {
    dob: string;
    parentEmail: string;
    name: string;
    parentPhone: string;
    photoUrl: string;
    classId: ClassId;
    admissionNumber: string;
    academicYear: string;
    sectionId: bigint;
    rollNumber: string;
    address: string;
    gender: string;
    parentName: string;
}
export type Result_5 = {
    __kind__: "ok";
    ok: Receipt;
} | {
    __kind__: "err";
    err: string;
};
export type BillId = bigint;
export type Result_1 = {
    __kind__: "ok";
    ok: FeeStructure;
} | {
    __kind__: "err";
    err: string;
};
export type ReceiptId = bigint;
export type Result_4 = {
    __kind__: "ok";
    ok: User;
} | {
    __kind__: "err";
    err: string;
};
export interface Receipt {
    id: ReceiptId;
    method: PaymentMethod;
    studentId: StudentId;
    isDuplicate: boolean;
    paymentId: PaymentId;
    paymentDate: Timestamp;
    issuedAt: Timestamp;
    amount: bigint;
    billId: BillId;
    receiptNumber: string;
    qrData: string;
}
export interface FeeStructure {
    id: FeeStructureId;
    createdAt: Timestamp;
    discountPercent: bigint;
    classId: ClassId;
    dueDayOfMonth: bigint;
    isActive: boolean;
    academicYear: string;
    category: FeeCategory;
    fineRatePercent: bigint;
    paymentPlan: PaymentPlan;
    amount: bigint;
    customCategoryName: string;
}
export type AuditLogId = bigint;
export interface ReceiptFilter {
    studentId?: StudentId;
    dateTo?: Timestamp;
    dateFrom?: Timestamp;
}
export interface PaymentInput {
    method: PaymentMethod;
    studentId: StudentId;
    referenceNumber: string;
    notes: string;
    amount: bigint;
    billId: BillId;
}
export type Result_7 = {
    __kind__: "ok";
    ok: Array<User>;
} | {
    __kind__: "err";
    err: string;
};
export type ClassId = bigint;
export interface Student {
    id: StudentId;
    dob: string;
    parentEmail: string;
    status: StudentStatus;
    name: string;
    createdAt: Timestamp;
    parentPhone: string;
    photoUrl: string;
    classId: ClassId;
    admissionNumber: string;
    academicYear: string;
    sectionId: bigint;
    rollNumber: string;
    address: string;
    gender: string;
    parentName: string;
}
export interface ClassInput {
    classTeacherId?: UserId;
    name: string;
    section: string;
    academicYear: string;
    capacity: bigint;
}
export type Result_6 = {
    __kind__: "ok";
    ok: boolean;
} | {
    __kind__: "err";
    err: string;
};
export interface User {
    id: UserId;
    status: UserStatus;
    principal: Principal;
    name: string;
    createdAt: Timestamp;
    role: Role;
    email: string;
    lastLogin: Timestamp;
}
export interface AuditLogFilter {
    dateTo?: Timestamp;
    userId?: UserId;
    entityType?: string;
    dateFrom?: Timestamp;
}
export type FeeStructureId = bigint;
export interface Payment {
    id: PaymentId;
    method: PaymentMethod;
    studentId: StudentId;
    referenceNumber: string;
    createdAt: Timestamp;
    notes: string;
    paymentDate: Timestamp;
    receiptId?: ReceiptId;
    amount: bigint;
    billId: BillId;
}
export type Result_9 = {
    __kind__: "ok";
    ok: Notification;
} | {
    __kind__: "err";
    err: string;
};
export type StudentId = bigint;
export interface DashboardStats {
    todayCollection: bigint;
    totalCollected: bigint;
    totalStudents: bigint;
    dueStudentsCount: bigint;
    pendingFees: bigint;
}
export type UserId = bigint;
export type Result = {
    __kind__: "ok";
    ok: Student;
} | {
    __kind__: "err";
    err: string;
};
export type Result_3 = {
    __kind__: "ok";
    ok: Bill;
} | {
    __kind__: "err";
    err: string;
};
export type PaymentId = bigint;
export type NotificationId = bigint;
export type Result_8 = {
    __kind__: "ok";
    ok: Array<Bill>;
} | {
    __kind__: "err";
    err: string;
};
export interface PaymentFilter {
    method?: PaymentMethod;
    studentId?: StudentId;
    dateTo?: Timestamp;
    dateFrom?: Timestamp;
}
export interface Notification {
    id: NotificationId;
    studentId: StudentId;
    notifType: NotificationType;
    createdAt: Timestamp;
    isRead: boolean;
    message: string;
    recipientPrincipal: Principal;
}
export interface BillFilter {
    status?: BillStatus;
    month?: string;
    studentId?: StudentId;
    classId?: ClassId;
}
export interface FeeStructureInput {
    discountPercent: bigint;
    classId: ClassId;
    dueDayOfMonth: bigint;
    academicYear: string;
    category: FeeCategory;
    fineRatePercent: bigint;
    paymentPlan: PaymentPlan;
    amount: bigint;
    customCategoryName: string;
}
export interface Bill {
    id: BillId;
    status: BillStatus;
    month: string;
    netAmount: bigint;
    studentId: StudentId;
    fineAmount: bigint;
    discountAmount: bigint;
    createdAt: Timestamp;
    dueDate: Timestamp;
    classId: ClassId;
    academicYear: string;
    totalAmount: bigint;
    billNumber: string;
    feeComponents: Array<FeeComponent>;
}
export enum BillStatus {
    Paid = "Paid",
    Overdue = "Overdue",
    Partial_ = "Partial",
    Cancelled = "Cancelled",
    Pending = "Pending"
}
export enum FeeCategory {
    Library = "Library",
    Admission = "Admission",
    Exam = "Exam",
    Tuition = "Tuition",
    Custom = "Custom",
    Miscellaneous = "Miscellaneous",
    Transport = "Transport",
    Hostel = "Hostel"
}
export enum NotificationType {
    FeeReminder = "FeeReminder",
    BillGenerated = "BillGenerated",
    PaymentConfirmation = "PaymentConfirmation",
    OverdueAlert = "OverdueAlert"
}
export enum PaymentMethod {
    UPI = "UPI",
    Card = "Card",
    Cash = "Cash",
    Online = "Online",
    BankTransfer = "BankTransfer"
}
export enum PaymentPlan {
    Quarterly = "Quarterly",
    Monthly = "Monthly",
    Yearly = "Yearly"
}
export enum Role {
    Teacher = "Teacher",
    SuperAdmin = "SuperAdmin",
    SchoolAdmin = "SchoolAdmin",
    Accountant = "Accountant"
}
export enum UserStatus {
    Inactive = "Inactive",
    Active = "Active"
}
export interface backendInterface {
    addAuditLog(action: string, entityType: string, entityId: bigint, oldValue: string, newValue: string): Promise<Result_6>;
    addClass(input: ClassInput): Promise<Result_2>;
    addNotification(notifType: NotificationType, studentId: StudentId, message: string): Promise<Result_9>;
    addStudent(input: StudentInput): Promise<Result>;
    createFeeStructure(input: FeeStructureInput): Promise<Result_1>;
    deleteClass(id: ClassId): Promise<Result_6>;
    deleteFeeStructure(id: FeeStructureId): Promise<Result_6>;
    deleteStudent(id: StudentId): Promise<Result_6>;
    duplicateReceipt(id: ReceiptId): Promise<Result_5>;
    generateBills(classId: ClassId, academicYear: string, month: string): Promise<Result_8>;
    getAuditLogs(filter: AuditLogFilter): Promise<Array<AuditLog>>;
    getBill(id: BillId): Promise<Bill | null>;
    getBills(filter: BillFilter): Promise<Array<Bill>>;
    getClass(id: ClassId): Promise<Class | null>;
    getClasses(academicYear: string | null): Promise<Array<Class>>;
    getFeeStructures(classId: ClassId | null, academicYear: string | null): Promise<Array<FeeStructure>>;
    getNotifications(): Promise<Array<Notification>>;
    getPayments(filter: PaymentFilter): Promise<Array<Payment>>;
    getReceipt(id: ReceiptId): Promise<Receipt | null>;
    getReceipts(filter: ReceiptFilter): Promise<Array<Receipt>>;
    getStats(): Promise<DashboardStats>;
    getStudent(id: StudentId): Promise<Student | null>;
    getStudents(filter: StudentFilter): Promise<Array<Student>>;
    getUserByPrincipal(): Promise<User | null>;
    listUsers(): Promise<Result_7>;
    markNotificationRead(id: NotificationId): Promise<Result_6>;
    recordPayment(input: PaymentInput): Promise<Result_5>;
    registerUser(name: string, email: string, role: Role): Promise<Result_4>;
    updateBillStatus(billId: BillId, status: BillStatus): Promise<Result_3>;
    updateClass(id: ClassId, input: ClassInput): Promise<Result_2>;
    updateFeeStructure(id: FeeStructureId, input: FeeStructureInput): Promise<Result_1>;
    updateLastLogin(): Promise<void>;
    updateStudent(id: StudentId, input: StudentInput): Promise<Result>;
}
import type { AuditLogFilter as _AuditLogFilter, Bill as _Bill, BillFilter as _BillFilter, BillId as _BillId, BillStatus as _BillStatus, Class as _Class, ClassId as _ClassId, ClassInput as _ClassInput, FeeCategory as _FeeCategory, FeeComponent as _FeeComponent, FeeStructure as _FeeStructure, FeeStructureId as _FeeStructureId, FeeStructureInput as _FeeStructureInput, Notification as _Notification, NotificationId as _NotificationId, NotificationType as _NotificationType, Payment as _Payment, PaymentFilter as _PaymentFilter, PaymentId as _PaymentId, PaymentInput as _PaymentInput, PaymentMethod as _PaymentMethod, PaymentPlan as _PaymentPlan, Receipt as _Receipt, ReceiptFilter as _ReceiptFilter, ReceiptId as _ReceiptId, Result as _Result, Result_1 as _Result_1, Result_2 as _Result_2, Result_3 as _Result_3, Result_4 as _Result_4, Result_5 as _Result_5, Result_6 as _Result_6, Result_7 as _Result_7, Result_8 as _Result_8, Result_9 as _Result_9, Role as _Role, Student as _Student, StudentFilter as _StudentFilter, StudentId as _StudentId, StudentStatus as _StudentStatus, Timestamp as _Timestamp, User as _User, UserId as _UserId, UserStatus as _UserStatus } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async addAuditLog(arg0: string, arg1: string, arg2: bigint, arg3: string, arg4: string): Promise<Result_6> {
        if (this.processError) {
            try {
                const result = await this.actor.addAuditLog(arg0, arg1, arg2, arg3, arg4);
                return from_candid_Result_6_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addAuditLog(arg0, arg1, arg2, arg3, arg4);
            return from_candid_Result_6_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async addClass(arg0: ClassInput): Promise<Result_2> {
        if (this.processError) {
            try {
                const result = await this.actor.addClass(to_candid_ClassInput_n3(this._uploadFile, this._downloadFile, arg0));
                return from_candid_Result_2_n5(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addClass(to_candid_ClassInput_n3(this._uploadFile, this._downloadFile, arg0));
            return from_candid_Result_2_n5(this._uploadFile, this._downloadFile, result);
        }
    }
    async addNotification(arg0: NotificationType, arg1: StudentId, arg2: string): Promise<Result_9> {
        if (this.processError) {
            try {
                const result = await this.actor.addNotification(to_candid_NotificationType_n10(this._uploadFile, this._downloadFile, arg0), arg1, arg2);
                return from_candid_Result_9_n12(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addNotification(to_candid_NotificationType_n10(this._uploadFile, this._downloadFile, arg0), arg1, arg2);
            return from_candid_Result_9_n12(this._uploadFile, this._downloadFile, result);
        }
    }
    async addStudent(arg0: StudentInput): Promise<Result> {
        if (this.processError) {
            try {
                const result = await this.actor.addStudent(arg0);
                return from_candid_Result_n18(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addStudent(arg0);
            return from_candid_Result_n18(this._uploadFile, this._downloadFile, result);
        }
    }
    async createFeeStructure(arg0: FeeStructureInput): Promise<Result_1> {
        if (this.processError) {
            try {
                const result = await this.actor.createFeeStructure(to_candid_FeeStructureInput_n24(this._uploadFile, this._downloadFile, arg0));
                return from_candid_Result_1_n30(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createFeeStructure(to_candid_FeeStructureInput_n24(this._uploadFile, this._downloadFile, arg0));
            return from_candid_Result_1_n30(this._uploadFile, this._downloadFile, result);
        }
    }
    async deleteClass(arg0: ClassId): Promise<Result_6> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteClass(arg0);
                return from_candid_Result_6_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteClass(arg0);
            return from_candid_Result_6_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async deleteFeeStructure(arg0: FeeStructureId): Promise<Result_6> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteFeeStructure(arg0);
                return from_candid_Result_6_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteFeeStructure(arg0);
            return from_candid_Result_6_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async deleteStudent(arg0: StudentId): Promise<Result_6> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteStudent(arg0);
                return from_candid_Result_6_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteStudent(arg0);
            return from_candid_Result_6_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async duplicateReceipt(arg0: ReceiptId): Promise<Result_5> {
        if (this.processError) {
            try {
                const result = await this.actor.duplicateReceipt(arg0);
                return from_candid_Result_5_n38(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.duplicateReceipt(arg0);
            return from_candid_Result_5_n38(this._uploadFile, this._downloadFile, result);
        }
    }
    async generateBills(arg0: ClassId, arg1: string, arg2: string): Promise<Result_8> {
        if (this.processError) {
            try {
                const result = await this.actor.generateBills(arg0, arg1, arg2);
                return from_candid_Result_8_n44(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.generateBills(arg0, arg1, arg2);
            return from_candid_Result_8_n44(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAuditLogs(arg0: AuditLogFilter): Promise<Array<AuditLog>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAuditLogs(to_candid_AuditLogFilter_n54(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAuditLogs(to_candid_AuditLogFilter_n54(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async getBill(arg0: BillId): Promise<Bill | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getBill(arg0);
                return from_candid_opt_n56(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getBill(arg0);
            return from_candid_opt_n56(this._uploadFile, this._downloadFile, result);
        }
    }
    async getBills(arg0: BillFilter): Promise<Array<Bill>> {
        if (this.processError) {
            try {
                const result = await this.actor.getBills(to_candid_BillFilter_n57(this._uploadFile, this._downloadFile, arg0));
                return from_candid_vec_n46(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getBills(to_candid_BillFilter_n57(this._uploadFile, this._downloadFile, arg0));
            return from_candid_vec_n46(this._uploadFile, this._downloadFile, result);
        }
    }
    async getClass(arg0: ClassId): Promise<Class | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getClass(arg0);
                return from_candid_opt_n61(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getClass(arg0);
            return from_candid_opt_n61(this._uploadFile, this._downloadFile, result);
        }
    }
    async getClasses(arg0: string | null): Promise<Array<Class>> {
        if (this.processError) {
            try {
                const result = await this.actor.getClasses(to_candid_opt_n62(this._uploadFile, this._downloadFile, arg0));
                return from_candid_vec_n63(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getClasses(to_candid_opt_n62(this._uploadFile, this._downloadFile, arg0));
            return from_candid_vec_n63(this._uploadFile, this._downloadFile, result);
        }
    }
    async getFeeStructures(arg0: ClassId | null, arg1: string | null): Promise<Array<FeeStructure>> {
        if (this.processError) {
            try {
                const result = await this.actor.getFeeStructures(to_candid_opt_n64(this._uploadFile, this._downloadFile, arg0), to_candid_opt_n62(this._uploadFile, this._downloadFile, arg1));
                return from_candid_vec_n65(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getFeeStructures(to_candid_opt_n64(this._uploadFile, this._downloadFile, arg0), to_candid_opt_n62(this._uploadFile, this._downloadFile, arg1));
            return from_candid_vec_n65(this._uploadFile, this._downloadFile, result);
        }
    }
    async getNotifications(): Promise<Array<Notification>> {
        if (this.processError) {
            try {
                const result = await this.actor.getNotifications();
                return from_candid_vec_n66(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getNotifications();
            return from_candid_vec_n66(this._uploadFile, this._downloadFile, result);
        }
    }
    async getPayments(arg0: PaymentFilter): Promise<Array<Payment>> {
        if (this.processError) {
            try {
                const result = await this.actor.getPayments(to_candid_PaymentFilter_n67(this._uploadFile, this._downloadFile, arg0));
                return from_candid_vec_n71(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPayments(to_candid_PaymentFilter_n67(this._uploadFile, this._downloadFile, arg0));
            return from_candid_vec_n71(this._uploadFile, this._downloadFile, result);
        }
    }
    async getReceipt(arg0: ReceiptId): Promise<Receipt | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getReceipt(arg0);
                return from_candid_opt_n75(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getReceipt(arg0);
            return from_candid_opt_n75(this._uploadFile, this._downloadFile, result);
        }
    }
    async getReceipts(arg0: ReceiptFilter): Promise<Array<Receipt>> {
        if (this.processError) {
            try {
                const result = await this.actor.getReceipts(to_candid_ReceiptFilter_n76(this._uploadFile, this._downloadFile, arg0));
                return from_candid_vec_n78(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getReceipts(to_candid_ReceiptFilter_n76(this._uploadFile, this._downloadFile, arg0));
            return from_candid_vec_n78(this._uploadFile, this._downloadFile, result);
        }
    }
    async getStats(): Promise<DashboardStats> {
        if (this.processError) {
            try {
                const result = await this.actor.getStats();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getStats();
            return result;
        }
    }
    async getStudent(arg0: StudentId): Promise<Student | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getStudent(arg0);
                return from_candid_opt_n79(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getStudent(arg0);
            return from_candid_opt_n79(this._uploadFile, this._downloadFile, result);
        }
    }
    async getStudents(arg0: StudentFilter): Promise<Array<Student>> {
        if (this.processError) {
            try {
                const result = await this.actor.getStudents(to_candid_StudentFilter_n80(this._uploadFile, this._downloadFile, arg0));
                return from_candid_vec_n84(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getStudents(to_candid_StudentFilter_n80(this._uploadFile, this._downloadFile, arg0));
            return from_candid_vec_n84(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserByPrincipal(): Promise<User | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserByPrincipal();
                return from_candid_opt_n85(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserByPrincipal();
            return from_candid_opt_n85(this._uploadFile, this._downloadFile, result);
        }
    }
    async listUsers(): Promise<Result_7> {
        if (this.processError) {
            try {
                const result = await this.actor.listUsers();
                return from_candid_Result_7_n91(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listUsers();
            return from_candid_Result_7_n91(this._uploadFile, this._downloadFile, result);
        }
    }
    async markNotificationRead(arg0: NotificationId): Promise<Result_6> {
        if (this.processError) {
            try {
                const result = await this.actor.markNotificationRead(arg0);
                return from_candid_Result_6_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.markNotificationRead(arg0);
            return from_candid_Result_6_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async recordPayment(arg0: PaymentInput): Promise<Result_5> {
        if (this.processError) {
            try {
                const result = await this.actor.recordPayment(to_candid_PaymentInput_n94(this._uploadFile, this._downloadFile, arg0));
                return from_candid_Result_5_n38(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.recordPayment(to_candid_PaymentInput_n94(this._uploadFile, this._downloadFile, arg0));
            return from_candid_Result_5_n38(this._uploadFile, this._downloadFile, result);
        }
    }
    async registerUser(arg0: string, arg1: string, arg2: Role): Promise<Result_4> {
        if (this.processError) {
            try {
                const result = await this.actor.registerUser(arg0, arg1, to_candid_Role_n96(this._uploadFile, this._downloadFile, arg2));
                return from_candid_Result_4_n98(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.registerUser(arg0, arg1, to_candid_Role_n96(this._uploadFile, this._downloadFile, arg2));
            return from_candid_Result_4_n98(this._uploadFile, this._downloadFile, result);
        }
    }
    async updateBillStatus(arg0: BillId, arg1: BillStatus): Promise<Result_3> {
        if (this.processError) {
            try {
                const result = await this.actor.updateBillStatus(arg0, to_candid_BillStatus_n59(this._uploadFile, this._downloadFile, arg1));
                return from_candid_Result_3_n100(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateBillStatus(arg0, to_candid_BillStatus_n59(this._uploadFile, this._downloadFile, arg1));
            return from_candid_Result_3_n100(this._uploadFile, this._downloadFile, result);
        }
    }
    async updateClass(arg0: ClassId, arg1: ClassInput): Promise<Result_2> {
        if (this.processError) {
            try {
                const result = await this.actor.updateClass(arg0, to_candid_ClassInput_n3(this._uploadFile, this._downloadFile, arg1));
                return from_candid_Result_2_n5(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateClass(arg0, to_candid_ClassInput_n3(this._uploadFile, this._downloadFile, arg1));
            return from_candid_Result_2_n5(this._uploadFile, this._downloadFile, result);
        }
    }
    async updateFeeStructure(arg0: FeeStructureId, arg1: FeeStructureInput): Promise<Result_1> {
        if (this.processError) {
            try {
                const result = await this.actor.updateFeeStructure(arg0, to_candid_FeeStructureInput_n24(this._uploadFile, this._downloadFile, arg1));
                return from_candid_Result_1_n30(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateFeeStructure(arg0, to_candid_FeeStructureInput_n24(this._uploadFile, this._downloadFile, arg1));
            return from_candid_Result_1_n30(this._uploadFile, this._downloadFile, result);
        }
    }
    async updateLastLogin(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateLastLogin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateLastLogin();
            return result;
        }
    }
    async updateStudent(arg0: StudentId, arg1: StudentInput): Promise<Result> {
        if (this.processError) {
            try {
                const result = await this.actor.updateStudent(arg0, arg1);
                return from_candid_Result_n18(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateStudent(arg0, arg1);
            return from_candid_Result_n18(this._uploadFile, this._downloadFile, result);
        }
    }
}
function from_candid_BillStatus_n49(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _BillStatus): BillStatus {
    return from_candid_variant_n50(_uploadFile, _downloadFile, value);
}
function from_candid_Bill_n47(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Bill): Bill {
    return from_candid_record_n48(_uploadFile, _downloadFile, value);
}
function from_candid_Class_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Class): Class {
    return from_candid_record_n8(_uploadFile, _downloadFile, value);
}
function from_candid_FeeCategory_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _FeeCategory): FeeCategory {
    return from_candid_variant_n35(_uploadFile, _downloadFile, value);
}
function from_candid_FeeComponent_n52(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _FeeComponent): FeeComponent {
    return from_candid_record_n53(_uploadFile, _downloadFile, value);
}
function from_candid_FeeStructure_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _FeeStructure): FeeStructure {
    return from_candid_record_n33(_uploadFile, _downloadFile, value);
}
function from_candid_NotificationType_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _NotificationType): NotificationType {
    return from_candid_variant_n17(_uploadFile, _downloadFile, value);
}
function from_candid_Notification_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Notification): Notification {
    return from_candid_record_n15(_uploadFile, _downloadFile, value);
}
function from_candid_PaymentMethod_n42(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _PaymentMethod): PaymentMethod {
    return from_candid_variant_n43(_uploadFile, _downloadFile, value);
}
function from_candid_PaymentPlan_n36(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _PaymentPlan): PaymentPlan {
    return from_candid_variant_n37(_uploadFile, _downloadFile, value);
}
function from_candid_Payment_n72(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Payment): Payment {
    return from_candid_record_n73(_uploadFile, _downloadFile, value);
}
function from_candid_Receipt_n40(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Receipt): Receipt {
    return from_candid_record_n41(_uploadFile, _downloadFile, value);
}
function from_candid_Result_1_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Result_1): Result_1 {
    return from_candid_variant_n31(_uploadFile, _downloadFile, value);
}
function from_candid_Result_2_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Result_2): Result_2 {
    return from_candid_variant_n6(_uploadFile, _downloadFile, value);
}
function from_candid_Result_3_n100(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Result_3): Result_3 {
    return from_candid_variant_n101(_uploadFile, _downloadFile, value);
}
function from_candid_Result_4_n98(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Result_4): Result_4 {
    return from_candid_variant_n99(_uploadFile, _downloadFile, value);
}
function from_candid_Result_5_n38(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Result_5): Result_5 {
    return from_candid_variant_n39(_uploadFile, _downloadFile, value);
}
function from_candid_Result_6_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Result_6): Result_6 {
    return from_candid_variant_n2(_uploadFile, _downloadFile, value);
}
function from_candid_Result_7_n91(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Result_7): Result_7 {
    return from_candid_variant_n92(_uploadFile, _downloadFile, value);
}
function from_candid_Result_8_n44(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Result_8): Result_8 {
    return from_candid_variant_n45(_uploadFile, _downloadFile, value);
}
function from_candid_Result_9_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Result_9): Result_9 {
    return from_candid_variant_n13(_uploadFile, _downloadFile, value);
}
function from_candid_Result_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Result): Result {
    return from_candid_variant_n19(_uploadFile, _downloadFile, value);
}
function from_candid_Role_n89(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Role): Role {
    return from_candid_variant_n90(_uploadFile, _downloadFile, value);
}
function from_candid_StudentStatus_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _StudentStatus): StudentStatus {
    return from_candid_variant_n23(_uploadFile, _downloadFile, value);
}
function from_candid_Student_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Student): Student {
    return from_candid_record_n21(_uploadFile, _downloadFile, value);
}
function from_candid_UserStatus_n88(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserStatus): UserStatus {
    return from_candid_variant_n23(_uploadFile, _downloadFile, value);
}
function from_candid_User_n86(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _User): User {
    return from_candid_record_n87(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n56(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Bill]): Bill | null {
    return value.length === 0 ? null : from_candid_Bill_n47(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n61(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Class]): Class | null {
    return value.length === 0 ? null : from_candid_Class_n7(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n74(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_ReceiptId]): ReceiptId | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n75(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Receipt]): Receipt | null {
    return value.length === 0 ? null : from_candid_Receipt_n40(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n79(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Student]): Student | null {
    return value.length === 0 ? null : from_candid_Student_n20(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n85(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_User]): User | null {
    return value.length === 0 ? null : from_candid_User_n86(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserId]): UserId | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _NotificationId;
    studentId: _StudentId;
    notifType: _NotificationType;
    createdAt: _Timestamp;
    isRead: boolean;
    message: string;
    recipientPrincipal: Principal;
}): {
    id: NotificationId;
    studentId: StudentId;
    notifType: NotificationType;
    createdAt: Timestamp;
    isRead: boolean;
    message: string;
    recipientPrincipal: Principal;
} {
    return {
        id: value.id,
        studentId: value.studentId,
        notifType: from_candid_NotificationType_n16(_uploadFile, _downloadFile, value.notifType),
        createdAt: value.createdAt,
        isRead: value.isRead,
        message: value.message,
        recipientPrincipal: value.recipientPrincipal
    };
}
function from_candid_record_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _StudentId;
    dob: string;
    parentEmail: string;
    status: _StudentStatus;
    name: string;
    createdAt: _Timestamp;
    parentPhone: string;
    photoUrl: string;
    classId: _ClassId;
    admissionNumber: string;
    academicYear: string;
    sectionId: bigint;
    rollNumber: string;
    address: string;
    gender: string;
    parentName: string;
}): {
    id: StudentId;
    dob: string;
    parentEmail: string;
    status: StudentStatus;
    name: string;
    createdAt: Timestamp;
    parentPhone: string;
    photoUrl: string;
    classId: ClassId;
    admissionNumber: string;
    academicYear: string;
    sectionId: bigint;
    rollNumber: string;
    address: string;
    gender: string;
    parentName: string;
} {
    return {
        id: value.id,
        dob: value.dob,
        parentEmail: value.parentEmail,
        status: from_candid_StudentStatus_n22(_uploadFile, _downloadFile, value.status),
        name: value.name,
        createdAt: value.createdAt,
        parentPhone: value.parentPhone,
        photoUrl: value.photoUrl,
        classId: value.classId,
        admissionNumber: value.admissionNumber,
        academicYear: value.academicYear,
        sectionId: value.sectionId,
        rollNumber: value.rollNumber,
        address: value.address,
        gender: value.gender,
        parentName: value.parentName
    };
}
function from_candid_record_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _FeeStructureId;
    createdAt: _Timestamp;
    discountPercent: bigint;
    classId: _ClassId;
    dueDayOfMonth: bigint;
    isActive: boolean;
    academicYear: string;
    category: _FeeCategory;
    fineRatePercent: bigint;
    paymentPlan: _PaymentPlan;
    amount: bigint;
    customCategoryName: string;
}): {
    id: FeeStructureId;
    createdAt: Timestamp;
    discountPercent: bigint;
    classId: ClassId;
    dueDayOfMonth: bigint;
    isActive: boolean;
    academicYear: string;
    category: FeeCategory;
    fineRatePercent: bigint;
    paymentPlan: PaymentPlan;
    amount: bigint;
    customCategoryName: string;
} {
    return {
        id: value.id,
        createdAt: value.createdAt,
        discountPercent: value.discountPercent,
        classId: value.classId,
        dueDayOfMonth: value.dueDayOfMonth,
        isActive: value.isActive,
        academicYear: value.academicYear,
        category: from_candid_FeeCategory_n34(_uploadFile, _downloadFile, value.category),
        fineRatePercent: value.fineRatePercent,
        paymentPlan: from_candid_PaymentPlan_n36(_uploadFile, _downloadFile, value.paymentPlan),
        amount: value.amount,
        customCategoryName: value.customCategoryName
    };
}
function from_candid_record_n41(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _ReceiptId;
    method: _PaymentMethod;
    studentId: _StudentId;
    isDuplicate: boolean;
    paymentId: _PaymentId;
    paymentDate: _Timestamp;
    issuedAt: _Timestamp;
    amount: bigint;
    billId: _BillId;
    receiptNumber: string;
    qrData: string;
}): {
    id: ReceiptId;
    method: PaymentMethod;
    studentId: StudentId;
    isDuplicate: boolean;
    paymentId: PaymentId;
    paymentDate: Timestamp;
    issuedAt: Timestamp;
    amount: bigint;
    billId: BillId;
    receiptNumber: string;
    qrData: string;
} {
    return {
        id: value.id,
        method: from_candid_PaymentMethod_n42(_uploadFile, _downloadFile, value.method),
        studentId: value.studentId,
        isDuplicate: value.isDuplicate,
        paymentId: value.paymentId,
        paymentDate: value.paymentDate,
        issuedAt: value.issuedAt,
        amount: value.amount,
        billId: value.billId,
        receiptNumber: value.receiptNumber,
        qrData: value.qrData
    };
}
function from_candid_record_n48(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _BillId;
    status: _BillStatus;
    month: string;
    netAmount: bigint;
    studentId: _StudentId;
    fineAmount: bigint;
    discountAmount: bigint;
    createdAt: _Timestamp;
    dueDate: _Timestamp;
    classId: _ClassId;
    academicYear: string;
    totalAmount: bigint;
    billNumber: string;
    feeComponents: Array<_FeeComponent>;
}): {
    id: BillId;
    status: BillStatus;
    month: string;
    netAmount: bigint;
    studentId: StudentId;
    fineAmount: bigint;
    discountAmount: bigint;
    createdAt: Timestamp;
    dueDate: Timestamp;
    classId: ClassId;
    academicYear: string;
    totalAmount: bigint;
    billNumber: string;
    feeComponents: Array<FeeComponent>;
} {
    return {
        id: value.id,
        status: from_candid_BillStatus_n49(_uploadFile, _downloadFile, value.status),
        month: value.month,
        netAmount: value.netAmount,
        studentId: value.studentId,
        fineAmount: value.fineAmount,
        discountAmount: value.discountAmount,
        createdAt: value.createdAt,
        dueDate: value.dueDate,
        classId: value.classId,
        academicYear: value.academicYear,
        totalAmount: value.totalAmount,
        billNumber: value.billNumber,
        feeComponents: from_candid_vec_n51(_uploadFile, _downloadFile, value.feeComponents)
    };
}
function from_candid_record_n53(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    fine: bigint;
    discount: bigint;
    category: _FeeCategory;
    amount: bigint;
}): {
    fine: bigint;
    discount: bigint;
    category: FeeCategory;
    amount: bigint;
} {
    return {
        fine: value.fine,
        discount: value.discount,
        category: from_candid_FeeCategory_n34(_uploadFile, _downloadFile, value.category),
        amount: value.amount
    };
}
function from_candid_record_n73(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _PaymentId;
    method: _PaymentMethod;
    studentId: _StudentId;
    referenceNumber: string;
    createdAt: _Timestamp;
    notes: string;
    paymentDate: _Timestamp;
    receiptId: [] | [_ReceiptId];
    amount: bigint;
    billId: _BillId;
}): {
    id: PaymentId;
    method: PaymentMethod;
    studentId: StudentId;
    referenceNumber: string;
    createdAt: Timestamp;
    notes: string;
    paymentDate: Timestamp;
    receiptId?: ReceiptId;
    amount: bigint;
    billId: BillId;
} {
    return {
        id: value.id,
        method: from_candid_PaymentMethod_n42(_uploadFile, _downloadFile, value.method),
        studentId: value.studentId,
        referenceNumber: value.referenceNumber,
        createdAt: value.createdAt,
        notes: value.notes,
        paymentDate: value.paymentDate,
        receiptId: record_opt_to_undefined(from_candid_opt_n74(_uploadFile, _downloadFile, value.receiptId)),
        amount: value.amount,
        billId: value.billId
    };
}
function from_candid_record_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _ClassId;
    classTeacherId: [] | [_UserId];
    name: string;
    createdAt: _Timestamp;
    section: string;
    academicYear: string;
    capacity: bigint;
    studentCount: bigint;
}): {
    id: ClassId;
    classTeacherId?: UserId;
    name: string;
    createdAt: Timestamp;
    section: string;
    academicYear: string;
    capacity: bigint;
    studentCount: bigint;
} {
    return {
        id: value.id,
        classTeacherId: record_opt_to_undefined(from_candid_opt_n9(_uploadFile, _downloadFile, value.classTeacherId)),
        name: value.name,
        createdAt: value.createdAt,
        section: value.section,
        academicYear: value.academicYear,
        capacity: value.capacity,
        studentCount: value.studentCount
    };
}
function from_candid_record_n87(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _UserId;
    status: _UserStatus;
    principal: Principal;
    name: string;
    createdAt: _Timestamp;
    role: _Role;
    email: string;
    lastLogin: _Timestamp;
}): {
    id: UserId;
    status: UserStatus;
    principal: Principal;
    name: string;
    createdAt: Timestamp;
    role: Role;
    email: string;
    lastLogin: Timestamp;
} {
    return {
        id: value.id,
        status: from_candid_UserStatus_n88(_uploadFile, _downloadFile, value.status),
        principal: value.principal,
        name: value.name,
        createdAt: value.createdAt,
        role: from_candid_Role_n89(_uploadFile, _downloadFile, value.role),
        email: value.email,
        lastLogin: value.lastLogin
    };
}
function from_candid_variant_n101(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: _Bill;
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: Bill;
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: from_candid_Bill_n47(_uploadFile, _downloadFile, value.ok)
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_variant_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: _Notification;
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: Notification;
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: from_candid_Notification_n14(_uploadFile, _downloadFile, value.ok)
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_variant_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    FeeReminder: null;
} | {
    BillGenerated: null;
} | {
    PaymentConfirmation: null;
} | {
    OverdueAlert: null;
}): NotificationType {
    return "FeeReminder" in value ? NotificationType.FeeReminder : "BillGenerated" in value ? NotificationType.BillGenerated : "PaymentConfirmation" in value ? NotificationType.PaymentConfirmation : "OverdueAlert" in value ? NotificationType.OverdueAlert : value;
}
function from_candid_variant_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: _Student;
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: Student;
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: from_candid_Student_n20(_uploadFile, _downloadFile, value.ok)
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_variant_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: boolean;
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: boolean;
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: value.ok
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_variant_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    Inactive: null;
} | {
    Active: null;
}): UserStatus {
    return "Inactive" in value ? UserStatus.Inactive : "Active" in value ? UserStatus.Active : value;
}
function from_candid_variant_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: _FeeStructure;
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: FeeStructure;
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: from_candid_FeeStructure_n32(_uploadFile, _downloadFile, value.ok)
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_variant_n35(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    Library: null;
} | {
    Admission: null;
} | {
    Exam: null;
} | {
    Tuition: null;
} | {
    Custom: null;
} | {
    Miscellaneous: null;
} | {
    Transport: null;
} | {
    Hostel: null;
}): FeeCategory {
    return "Library" in value ? FeeCategory.Library : "Admission" in value ? FeeCategory.Admission : "Exam" in value ? FeeCategory.Exam : "Tuition" in value ? FeeCategory.Tuition : "Custom" in value ? FeeCategory.Custom : "Miscellaneous" in value ? FeeCategory.Miscellaneous : "Transport" in value ? FeeCategory.Transport : "Hostel" in value ? FeeCategory.Hostel : value;
}
function from_candid_variant_n37(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    Quarterly: null;
} | {
    Monthly: null;
} | {
    Yearly: null;
}): PaymentPlan {
    return "Quarterly" in value ? PaymentPlan.Quarterly : "Monthly" in value ? PaymentPlan.Monthly : "Yearly" in value ? PaymentPlan.Yearly : value;
}
function from_candid_variant_n39(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: _Receipt;
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: Receipt;
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: from_candid_Receipt_n40(_uploadFile, _downloadFile, value.ok)
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_variant_n43(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    UPI: null;
} | {
    Card: null;
} | {
    Cash: null;
} | {
    Online: null;
} | {
    BankTransfer: null;
}): PaymentMethod {
    return "UPI" in value ? PaymentMethod.UPI : "Card" in value ? PaymentMethod.Card : "Cash" in value ? PaymentMethod.Cash : "Online" in value ? PaymentMethod.Online : "BankTransfer" in value ? PaymentMethod.BankTransfer : value;
}
function from_candid_variant_n45(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: Array<_Bill>;
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: Array<Bill>;
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: from_candid_vec_n46(_uploadFile, _downloadFile, value.ok)
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_variant_n50(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    Paid: null;
} | {
    Overdue: null;
} | {
    Partial: null;
} | {
    Cancelled: null;
} | {
    Pending: null;
}): BillStatus {
    return "Paid" in value ? BillStatus.Paid : "Overdue" in value ? BillStatus.Overdue : "Partial" in value ? BillStatus.Partial : "Cancelled" in value ? BillStatus.Cancelled : "Pending" in value ? BillStatus.Pending : value;
}
function from_candid_variant_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: _Class;
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: Class;
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: from_candid_Class_n7(_uploadFile, _downloadFile, value.ok)
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_variant_n90(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    Teacher: null;
} | {
    SuperAdmin: null;
} | {
    SchoolAdmin: null;
} | {
    Accountant: null;
}): Role {
    return "Teacher" in value ? Role.Teacher : "SuperAdmin" in value ? Role.SuperAdmin : "SchoolAdmin" in value ? Role.SchoolAdmin : "Accountant" in value ? Role.Accountant : value;
}
function from_candid_variant_n92(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: Array<_User>;
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: Array<User>;
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: from_candid_vec_n93(_uploadFile, _downloadFile, value.ok)
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_variant_n99(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: _User;
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: User;
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: from_candid_User_n86(_uploadFile, _downloadFile, value.ok)
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_vec_n46(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Bill>): Array<Bill> {
    return value.map((x)=>from_candid_Bill_n47(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n51(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_FeeComponent>): Array<FeeComponent> {
    return value.map((x)=>from_candid_FeeComponent_n52(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n63(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Class>): Array<Class> {
    return value.map((x)=>from_candid_Class_n7(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n65(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_FeeStructure>): Array<FeeStructure> {
    return value.map((x)=>from_candid_FeeStructure_n32(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n66(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Notification>): Array<Notification> {
    return value.map((x)=>from_candid_Notification_n14(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n71(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Payment>): Array<Payment> {
    return value.map((x)=>from_candid_Payment_n72(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n78(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Receipt>): Array<Receipt> {
    return value.map((x)=>from_candid_Receipt_n40(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n84(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Student>): Array<Student> {
    return value.map((x)=>from_candid_Student_n20(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n93(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_User>): Array<User> {
    return value.map((x)=>from_candid_User_n86(_uploadFile, _downloadFile, x));
}
function to_candid_AuditLogFilter_n54(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: AuditLogFilter): _AuditLogFilter {
    return to_candid_record_n55(_uploadFile, _downloadFile, value);
}
function to_candid_BillFilter_n57(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: BillFilter): _BillFilter {
    return to_candid_record_n58(_uploadFile, _downloadFile, value);
}
function to_candid_BillStatus_n59(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: BillStatus): _BillStatus {
    return to_candid_variant_n60(_uploadFile, _downloadFile, value);
}
function to_candid_ClassInput_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ClassInput): _ClassInput {
    return to_candid_record_n4(_uploadFile, _downloadFile, value);
}
function to_candid_FeeCategory_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: FeeCategory): _FeeCategory {
    return to_candid_variant_n27(_uploadFile, _downloadFile, value);
}
function to_candid_FeeStructureInput_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: FeeStructureInput): _FeeStructureInput {
    return to_candid_record_n25(_uploadFile, _downloadFile, value);
}
function to_candid_NotificationType_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: NotificationType): _NotificationType {
    return to_candid_variant_n11(_uploadFile, _downloadFile, value);
}
function to_candid_PaymentFilter_n67(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: PaymentFilter): _PaymentFilter {
    return to_candid_record_n68(_uploadFile, _downloadFile, value);
}
function to_candid_PaymentInput_n94(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: PaymentInput): _PaymentInput {
    return to_candid_record_n95(_uploadFile, _downloadFile, value);
}
function to_candid_PaymentMethod_n69(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: PaymentMethod): _PaymentMethod {
    return to_candid_variant_n70(_uploadFile, _downloadFile, value);
}
function to_candid_PaymentPlan_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: PaymentPlan): _PaymentPlan {
    return to_candid_variant_n29(_uploadFile, _downloadFile, value);
}
function to_candid_ReceiptFilter_n76(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ReceiptFilter): _ReceiptFilter {
    return to_candid_record_n77(_uploadFile, _downloadFile, value);
}
function to_candid_Role_n96(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Role): _Role {
    return to_candid_variant_n97(_uploadFile, _downloadFile, value);
}
function to_candid_StudentFilter_n80(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: StudentFilter): _StudentFilter {
    return to_candid_record_n81(_uploadFile, _downloadFile, value);
}
function to_candid_StudentStatus_n82(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: StudentStatus): _StudentStatus {
    return to_candid_variant_n83(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n62(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: string | null): [] | [string] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_opt_n64(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ClassId | null): [] | [_ClassId] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_record_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    discountPercent: bigint;
    classId: ClassId;
    dueDayOfMonth: bigint;
    academicYear: string;
    category: FeeCategory;
    fineRatePercent: bigint;
    paymentPlan: PaymentPlan;
    amount: bigint;
    customCategoryName: string;
}): {
    discountPercent: bigint;
    classId: _ClassId;
    dueDayOfMonth: bigint;
    academicYear: string;
    category: _FeeCategory;
    fineRatePercent: bigint;
    paymentPlan: _PaymentPlan;
    amount: bigint;
    customCategoryName: string;
} {
    return {
        discountPercent: value.discountPercent,
        classId: value.classId,
        dueDayOfMonth: value.dueDayOfMonth,
        academicYear: value.academicYear,
        category: to_candid_FeeCategory_n26(_uploadFile, _downloadFile, value.category),
        fineRatePercent: value.fineRatePercent,
        paymentPlan: to_candid_PaymentPlan_n28(_uploadFile, _downloadFile, value.paymentPlan),
        amount: value.amount,
        customCategoryName: value.customCategoryName
    };
}
function to_candid_record_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    classTeacherId?: UserId;
    name: string;
    section: string;
    academicYear: string;
    capacity: bigint;
}): {
    classTeacherId: [] | [_UserId];
    name: string;
    section: string;
    academicYear: string;
    capacity: bigint;
} {
    return {
        classTeacherId: value.classTeacherId ? candid_some(value.classTeacherId) : candid_none(),
        name: value.name,
        section: value.section,
        academicYear: value.academicYear,
        capacity: value.capacity
    };
}
function to_candid_record_n55(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    dateTo?: Timestamp;
    userId?: UserId;
    entityType?: string;
    dateFrom?: Timestamp;
}): {
    dateTo: [] | [_Timestamp];
    userId: [] | [_UserId];
    entityType: [] | [string];
    dateFrom: [] | [_Timestamp];
} {
    return {
        dateTo: value.dateTo ? candid_some(value.dateTo) : candid_none(),
        userId: value.userId ? candid_some(value.userId) : candid_none(),
        entityType: value.entityType ? candid_some(value.entityType) : candid_none(),
        dateFrom: value.dateFrom ? candid_some(value.dateFrom) : candid_none()
    };
}
function to_candid_record_n58(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    status?: BillStatus;
    month?: string;
    studentId?: StudentId;
    classId?: ClassId;
}): {
    status: [] | [_BillStatus];
    month: [] | [string];
    studentId: [] | [_StudentId];
    classId: [] | [_ClassId];
} {
    return {
        status: value.status ? candid_some(to_candid_BillStatus_n59(_uploadFile, _downloadFile, value.status)) : candid_none(),
        month: value.month ? candid_some(value.month) : candid_none(),
        studentId: value.studentId ? candid_some(value.studentId) : candid_none(),
        classId: value.classId ? candid_some(value.classId) : candid_none()
    };
}
function to_candid_record_n68(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    method?: PaymentMethod;
    studentId?: StudentId;
    dateTo?: Timestamp;
    dateFrom?: Timestamp;
}): {
    method: [] | [_PaymentMethod];
    studentId: [] | [_StudentId];
    dateTo: [] | [_Timestamp];
    dateFrom: [] | [_Timestamp];
} {
    return {
        method: value.method ? candid_some(to_candid_PaymentMethod_n69(_uploadFile, _downloadFile, value.method)) : candid_none(),
        studentId: value.studentId ? candid_some(value.studentId) : candid_none(),
        dateTo: value.dateTo ? candid_some(value.dateTo) : candid_none(),
        dateFrom: value.dateFrom ? candid_some(value.dateFrom) : candid_none()
    };
}
function to_candid_record_n77(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    studentId?: StudentId;
    dateTo?: Timestamp;
    dateFrom?: Timestamp;
}): {
    studentId: [] | [_StudentId];
    dateTo: [] | [_Timestamp];
    dateFrom: [] | [_Timestamp];
} {
    return {
        studentId: value.studentId ? candid_some(value.studentId) : candid_none(),
        dateTo: value.dateTo ? candid_some(value.dateTo) : candid_none(),
        dateFrom: value.dateFrom ? candid_some(value.dateFrom) : candid_none()
    };
}
function to_candid_record_n81(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    status?: StudentStatus;
    classId?: ClassId;
    searchTerm?: string;
    academicYear?: string;
}): {
    status: [] | [_StudentStatus];
    classId: [] | [_ClassId];
    searchTerm: [] | [string];
    academicYear: [] | [string];
} {
    return {
        status: value.status ? candid_some(to_candid_StudentStatus_n82(_uploadFile, _downloadFile, value.status)) : candid_none(),
        classId: value.classId ? candid_some(value.classId) : candid_none(),
        searchTerm: value.searchTerm ? candid_some(value.searchTerm) : candid_none(),
        academicYear: value.academicYear ? candid_some(value.academicYear) : candid_none()
    };
}
function to_candid_record_n95(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    method: PaymentMethod;
    studentId: StudentId;
    referenceNumber: string;
    notes: string;
    amount: bigint;
    billId: BillId;
}): {
    method: _PaymentMethod;
    studentId: _StudentId;
    referenceNumber: string;
    notes: string;
    amount: bigint;
    billId: _BillId;
} {
    return {
        method: to_candid_PaymentMethod_n69(_uploadFile, _downloadFile, value.method),
        studentId: value.studentId,
        referenceNumber: value.referenceNumber,
        notes: value.notes,
        amount: value.amount,
        billId: value.billId
    };
}
function to_candid_variant_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: NotificationType): {
    FeeReminder: null;
} | {
    BillGenerated: null;
} | {
    PaymentConfirmation: null;
} | {
    OverdueAlert: null;
} {
    return value == NotificationType.FeeReminder ? {
        FeeReminder: null
    } : value == NotificationType.BillGenerated ? {
        BillGenerated: null
    } : value == NotificationType.PaymentConfirmation ? {
        PaymentConfirmation: null
    } : value == NotificationType.OverdueAlert ? {
        OverdueAlert: null
    } : value;
}
function to_candid_variant_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: FeeCategory): {
    Library: null;
} | {
    Admission: null;
} | {
    Exam: null;
} | {
    Tuition: null;
} | {
    Custom: null;
} | {
    Miscellaneous: null;
} | {
    Transport: null;
} | {
    Hostel: null;
} {
    return value == FeeCategory.Library ? {
        Library: null
    } : value == FeeCategory.Admission ? {
        Admission: null
    } : value == FeeCategory.Exam ? {
        Exam: null
    } : value == FeeCategory.Tuition ? {
        Tuition: null
    } : value == FeeCategory.Custom ? {
        Custom: null
    } : value == FeeCategory.Miscellaneous ? {
        Miscellaneous: null
    } : value == FeeCategory.Transport ? {
        Transport: null
    } : value == FeeCategory.Hostel ? {
        Hostel: null
    } : value;
}
function to_candid_variant_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: PaymentPlan): {
    Quarterly: null;
} | {
    Monthly: null;
} | {
    Yearly: null;
} {
    return value == PaymentPlan.Quarterly ? {
        Quarterly: null
    } : value == PaymentPlan.Monthly ? {
        Monthly: null
    } : value == PaymentPlan.Yearly ? {
        Yearly: null
    } : value;
}
function to_candid_variant_n60(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: BillStatus): {
    Paid: null;
} | {
    Overdue: null;
} | {
    Partial: null;
} | {
    Cancelled: null;
} | {
    Pending: null;
} {
    return value == BillStatus.Paid ? {
        Paid: null
    } : value == BillStatus.Overdue ? {
        Overdue: null
    } : value == BillStatus.Partial ? {
        Partial_: null
    } : value == BillStatus.Cancelled ? {
        Cancelled: null
    } : value == BillStatus.Pending ? {
        Pending: null
    } : value;
}
function to_candid_variant_n70(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: PaymentMethod): {
    UPI: null;
} | {
    Card: null;
} | {
    Cash: null;
} | {
    Online: null;
} | {
    BankTransfer: null;
} {
    return value == PaymentMethod.UPI ? {
        UPI: null
    } : value == PaymentMethod.Card ? {
        Card: null
    } : value == PaymentMethod.Cash ? {
        Cash: null
    } : value == PaymentMethod.Online ? {
        Online: null
    } : value == PaymentMethod.BankTransfer ? {
        BankTransfer: null
    } : value;
}
function to_candid_variant_n83(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserStatus): {
    Inactive: null;
} | {
    Active: null;
} {
    return value == UserStatus.Inactive ? {
        Inactive: null
    } : value == UserStatus.Active ? {
        Active: null
    } : value;
}
function to_candid_variant_n97(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Role): {
    Teacher: null;
} | {
    SuperAdmin: null;
} | {
    SchoolAdmin: null;
} | {
    Accountant: null;
} {
    return value == Role.Teacher ? {
        Teacher: null
    } : value == Role.SuperAdmin ? {
        SuperAdmin: null
    } : value == Role.SchoolAdmin ? {
        SchoolAdmin: null
    } : value == Role.Accountant ? {
        Accountant: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
